###  Criar um novo usuário
# spaceId: 1 -> pertencer_lideres
# role - adimin, manager, suport, user

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "login": "user_000002",
  "password": "user_000002",
  "spaceId": 1,
  "role": "user"
}

###  Login
# @name login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###  Gerar novo token (refresh)
POST http://localhost:3000/api/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

###  Logout
POST http://localhost:3000/api/logout
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

###  Acesso a rota protegida (status)
GET http://localhost:3000/api/status
Authorization: Bearer {{login.response.body.token}}


###  Buscar todos os usuários
GET http://localhost:3000/api/users
Authorization: Bearer {{login.response.body.token}}

###  Buscar usuário por ID
GET http://localhost:3000/api/users/1
Authorization: Bearer {{login.response.body.token}}


###  Atualizar usuário
PUT http://localhost:3000/api/users/2
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "login": "new_login_2",
  "password": "new_login_2"
}


###  Deletar usuário
DELETE http://localhost:3000/api/users/2
Authorization: Bearer {{login.response.body.token}}


### Consultar cursos do usuário
GET http://localhost:3000/api/users/3/courses
Content-Type: application/json





############################
## INÍCIO DA API DE CURSOS
############################

### Buscar dados do curso (básico)
GET http://localhost:3000/api/course/3
Content-Type: application/json
//Authorization: Bearer {{token}}

### Buscar unidades do curso do usuário
GET http://localhost:3000/api/units/3
Content-Type: application/json
//Authorization: Bearer {{token}}

### Buscar unidades do curso do usuário
GET http://localhost:3000/api/lessons/1
Content-Type: application/json
//Authorization: Bearer {{token}}

### Buscar curso completo do usuário
GET http://localhost:3000/api/user-courses/3/course
Content-Type: application/json
//Authorization: Bearer {{token}}

### Buscar configurações de user_course_settings
GET http://localhost:3000/api/settings/3
Content-Type: application/json
# Authorization: Bearer {{token}} 
### Atualizar configurações de user_course_settings

### Atualizar configurações (merge no config)
PUT http://localhost:3000/api/settings/3
Content-Type: application/json

{
  "selectedThemeKey": "dark_mono"
}


############################
## FIM DA API DE CURSOS
############################




### 🔹 Upload de imagem para a galeria do curso do usuário
POST http://localhost:3000/api/user-courses/3/gallery/upload
Content-Type: multipart/form-data; boundary=MYBOUNDARY
Authorization: Bearer {{login.response.body.token}}

--MYBOUNDARY
Content-Disposition: form-data; name="image"; filename="img.png"
Content-Type: image/png

< ./gallery_image_template.png
--MYBOUNDARY--im


### 🚀 Criar Múltiplos Usuários via CSV
# @name bulkCreateUsers
POST http://localhost:3000/api/users/bulk-upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="csvFile"; filename="usuarios_teste.csv"
Content-Type: text/csv

< ./bulk_create_user_temlpate.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 🔹 Buscar Space pelo nome (ex: pertencer_lideres)
GET http://localhost:3000/api/space/pertencer_lideres
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}