### 🔹 Criar um novo usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "login": "Teste Clone 66",
  "password": "123456",
  "spaceId": 1,
  "role": "admin"
}

### 🔹 Login
# @name login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "login": "Teste Clone 33",
  "password": "123456"
}

### 🔹 Gerar novo token (refresh)
POST http://localhost:3000/api/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

### 🔹 Logout
POST http://localhost:3000/api/logout
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

### 🔹 Acesso a rota protegida (status)
GET http://localhost:3000/api/status
Authorization: Bearer {{login.response.body.token}}


### 🔹 Buscar todos os usuários
GET http://localhost:3000/api/users
Authorization: Bearer {{login.response.body.token}}

### 🔹 Buscar usuário por ID
GET http://localhost:3000/api/users/51
Authorization: Bearer {{login.response.body.token}}


### 🔹 Atualizar usuário
PUT http://localhost:3000/api/users/51
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "login": "6666666666",
  "password": "666666"
}


### 🔹 Deletar usuário
DELETE http://localhost:3000/api/users/4
Authorization: Bearer {{login.response.body.token}}


### Consultar cursos do usuário
GET http://localhost:3000/api/users/52/courses
Content-Type: application/json


### Buscar curso completo do usuário
GET http://localhost:3000/api/user-courses/58/course
Content-Type: application/json


### 🔹 Upload de imagem para a galeria do curso do usuário
POST http://localhost:3000/api/user-courses/58/gallery/upload
Content-Type: multipart/form-data; boundary=MYBOUNDARY
Authorization: Bearer {{login.response.body.token}}

--MYBOUNDARY
Content-Disposition: form-data; name="image"; filename="img.png"
Content-Type: image/png

< /Users/tiagodiniz/Desktop/img.png
--MYBOUNDARY--im