version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: pertencer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pertencer_db
      MYSQL_USER: pertencer_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql # Persist data in a named volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  mysql_data:
